/*
 * This source file was generated by the Gradle 'init' task
 */
package io.nthcristian.zplrdr;

import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test
    void someLibraryMethodReturnsTrue() {

    }
}
